import { Pergunta, RegraTriagem } from '../types/triagem';
import { Unidade, Servico } from '../types/unidade';
import { Tenant } from '../types/tenant';

export const MOCK_TENANTS: Tenant[] = [
  {
    id: 'sao-luis',
    nome: 'Prefeitura de São Luís',
    municipio: 'São Luís',
    estado: 'MA',
    siteOficial: 'https://saoluis.ma.gov.br',
    contatoSuporte: 'Disque Saúde Municipal: 156',
    ativo: true,
  },
  {
    id: 'imperatriz',
    nome: 'Prefeitura de Imperatriz',
    municipio: 'Imperatriz',
    estado: 'MA',
    siteOficial: 'https://imperatriz.ma.gov.br',
    contatoSuporte: 'Disque Saúde: 0800 280 5000',
    ativo: true,
  },
  {
    id: 'rede-estadual',
    nome: 'Secretaria Estadual de Saúde - MA',
    municipio: 'Rede Estadual (Maranhão)',
    estado: 'MA',
    siteOficial: 'https://saude.ma.gov.br',
    contatoSuporte: 'Ouvidoria SUS: 136',
    ativo: true,
  },
];

export const MOCK_SERVICOS: Servico[] = [
  { id: 1, nome: 'Consulta Médica Geral', descricao: 'Atendimento médico de clínica geral e acompanhamento.', categoria: 'Atenção Básica' },
  { id: 2, nome: 'Vacinação', descricao: 'Aplicação de vacinas do calendário nacional de imunização.', categoria: 'Prevenção' },
  { id: 3, nome: 'Acompanhamento Hipertensão e Diabetes', descricao: 'Monitoramento contínuo de doenças crônicas (Hiperdia).', categoria: 'Atenção Básica' },
  { id: 4, nome: 'Pré-Natal e Saúde da Mulher', descricao: 'Acompanhamento gestacional, preventivo e consultas ginecológicas.', categoria: 'Saúde da Mulher' },
  { id: 5, nome: 'Saúde Bucal / Odontologia', descricao: 'Atendimento odontológico profilático e restaurações.', categoria: 'Odontologia' },
  { id: 6, nome: 'Curativos e Procedimentos Simples', descricao: 'Realização de curativos, retiradas de pontos e medicações.', categoria: 'Enfermagem' },
  { id: 7, nome: 'Testes Rápidos (ISTs / COVID)', descricao: 'Triagem e diagnóstico rápido com acompanhamento profissional.', categoria: 'Diagnóstico' },
  { id: 8, nome: 'Atendimento de Urgência 24h', descricao: 'Pronto atendimento para casos agudos de urgência.', categoria: 'Urgência' },
  { id: 9, nome: 'Estabilização de Emergência', descricao: 'Suporte avançado de vida e estabilização pré-hospitalar.', categoria: 'Emergência' },
  { id: 10, nome: 'Exames de Raio-X e ECG', descricao: 'Exames radiológicos e eletrocardiograma para pronto atendimento.', categoria: 'Exames' },
];

export const MOCK_UNIDADES: Unidade[] = [
  {
    id: 101,
    tenantId: 'sao-luis',
    nome: 'UBS Centro - Dra. Francisca Leite',
    tipo: 'UBS',
    endereco: 'Rua do Passeio, S/N',
    numero: '450',
    bairro: 'Centro',
    cidade: 'São Luís',
    estado: 'MA',
    cep: '65015-370',
    latitude: -2.5298,
    longitude: -44.3028,
    distanciaKm: 1.2,
    telefone: '(98) 3212-4000',
    horarioFuncionamento: 'Segunda a Sexta: 07:00 às 17:00',
    status: 'ABERTA',
    statusDescricao: 'Funcionamento normal da atenção básica.',
    ultimaAtualizacao: '15/08/2026 14:30',
    ativo: true,
    linhasOnibus: ['T084 Cohatrac / Terminal da Praia Grande', 'T062 Socorrão II / Rodoviária'],
    referencia: 'Próximo à Praça Deodoro',
    servicos: [MOCK_SERVICOS[0], MOCK_SERVICOS[1], MOCK_SERVICOS[2], MOCK_SERVICOS[3], MOCK_SERVICOS[4], MOCK_SERVICOS[5], MOCK_SERVICOS[6]],
  },
  {
    id: 102,
    tenantId: 'sao-luis',
    nome: 'UPA 24h Parque Piauí / Itaqui-Bacanga',
    tipo: 'UPA',
    endereco: 'Av. dos Portugueses',
    numero: '1200',
    bairro: 'Anjo da Guarda',
    cidade: 'São Luís',
    estado: 'MA',
    cep: '65085-580',
    latitude: -2.5562,
    longitude: -44.3114,
    distanciaKm: 3.5,
    telefone: '(98) 3214-8900',
    telefoneEmergencia: '(98) 3214-8901',
    horarioFuncionamento: 'Ininterrupto — 24 horas por dia (Todos os dias)',
    status: 'ABERTA',
    statusDescricao: 'Pronto atendimento 24h operando normalmente.',
    ultimaAtualizacao: '15/08/2026 15:00',
    ativo: true,
    linhasOnibus: ['T320 Maracanã / Terminal Praia Grande', 'T408 Vila Nova'],
    referencia: 'Em frente ao Campus da UFMA',
    servicos: [MOCK_SERVICOS[7], MOCK_SERVICOS[8], MOCK_SERVICOS[9], MOCK_SERVICOS[5]],
  },
  {
    id: 103,
    tenantId: 'sao-luis',
    nome: 'UBS Vinhais - Dr. Paulo Ramos',
    tipo: 'UBS',
    endereco: 'Alameda D, Conjunto Vinhais',
    numero: '88',
    bairro: 'Vinhais',
    cidade: 'São Luís',
    estado: 'MA',
    cep: '65071-120',
    latitude: -2.5089,
    longitude: -44.2612,
    distanciaKm: 4.8,
    telefone: '(98) 3236-1212',
    horarioFuncionamento: 'Segunda a Sexta: 07:00 às 18:00',
    status: 'ABERTA',
    statusDescricao: 'Atendimento de rotina e vacinação ativas.',
    ultimaAtualizacao: '15/08/2026 09:15',
    ativo: true,
    linhasOnibus: ['T053 Vinhais / Shopping', 'T064 Cohatrac III'],
    referencia: 'Atrás da Feira do Vinhais',
    servicos: [MOCK_SERVICOS[0], MOCK_SERVICOS[1], MOCK_SERVICOS[2], MOCK_SERVICOS[3], MOCK_SERVICOS[6]],
  },
  {
    id: 104,
    tenantId: 'sao-luis',
    nome: 'UPA 24h Cidade Operária',
    tipo: 'UPA',
    endereco: 'Av. Principal da Cidade Operária',
    numero: 'S/N',
    bairro: 'Cidade Operária',
    cidade: 'São Luís',
    estado: 'MA',
    cep: '65058-000',
    latitude: -2.5711,
    longitude: -44.2105,
    distanciaKm: 8.1,
    telefone: '(98) 3241-7788',
    telefoneEmergencia: '(98) 3241-7789',
    horarioFuncionamento: 'Ininterrupto — 24 horas por dia (Todos os dias)',
    status: 'ATENDIMENTO_ALTERADO',
    statusDescricao: 'Alta demanda de urgências pediátricas. Atendimento com prioridade para casos graves.',
    ultimaAtualizacao: '15/08/2026 13:45',
    ativo: true,
    linhasOnibus: ['T061 Cidade Operária', 'T070 UEMA / IPASE'],
    referencia: 'Próximo à Unidade Integrada UEMA',
    servicos: [MOCK_SERVICOS[7], MOCK_SERVICOS[8], MOCK_SERVICOS[9]],
  },
  {
    id: 105,
    tenantId: 'sao-luis',
    nome: 'Hospital Municipal Djalma Marques (Socorrão I)',
    tipo: 'HOSPITAL',
    endereco: 'Rua do Passeio',
    numero: '780',
    bairro: 'Centro',
    cidade: 'São Luís',
    estado: 'MA',
    cep: '65015-370',
    latitude: -2.5312,
    longitude: -44.3011,
    distanciaKm: 1.5,
    telefone: '(98) 3221-5000',
    telefoneEmergencia: '(98) 3221-5001',
    horarioFuncionamento: 'Emergência 24h por encaminhamento ou SAMU',
    status: 'ABERTA',
    statusDescricao: 'Unidade hospitalar de referência para urgências de alta complexidade.',
    ultimaAtualizacao: '15/08/2026 12:00',
    ativo: true,
    linhasOnibus: ['T084 Cohatrac', 'T062 Socorrão II'],
    referencia: 'Centro Histórico',
    servicos: [MOCK_SERVICOS[8], MOCK_SERVICOS[9]],
  },
  {
    id: 106,
    tenantId: 'imperatriz',
    nome: 'UBS Bacuri - Unidade da Família',
    tipo: 'UBS',
    endereco: 'Rua Urbano Santos',
    numero: '310',
    bairro: 'Bacuri',
    cidade: 'Imperatriz',
    estado: 'MA',
    cep: '65900-000',
    latitude: -5.5266,
    longitude: -47.4789,
    distanciaKm: 2.1,
    telefone: '(99) 3524-1100',
    horarioFuncionamento: 'Segunda a Sexta: 07:30 às 17:30',
    status: 'ABERTA',
    statusDescricao: 'Atendimento de saúde da família e vacinação.',
    ultimaAtualizacao: '15/08/2026 08:30',
    ativo: true,
    servicos: [MOCK_SERVICOS[0], MOCK_SERVICOS[1], MOCK_SERVICOS[2], MOCK_SERVICOS[3]],
  },
];

export const MOCK_PERGUNTAS: Pergunta[] = [
  {
    id: 1,
    ordem: 1,
    texto: 'O problema ou sintoma começou de forma repentina e intensa?',
    subtexto: 'Situações agudas que surgem em poucos minutos ou horas e evoluem rápido.',
    ativa: true,
    categoria: 'evolucao',
  },
  {
    id: 2,
    ordem: 2,
    texto: 'Existe dor forte ou pressão intensa no peito?',
    subtexto: 'Pressão no tórax que pode se espalhar para o braço, pescoço ou mandíbula.',
    ativa: true,
    categoria: 'emergencia',
  },
  {
    id: 3,
    ordem: 3,
    texto: 'Existe dificuldade importante ou falta de ar para respirar?',
    subtexto: 'Sensação de sufocamento, respiração muito rápida ou incapacidade de falar frases inteiras.',
    ativa: true,
    categoria: 'emergencia',
  },
  {
    id: 4,
    ordem: 4,
    texto: 'A pessoa desmaiou, perdeu a consciência ou está confusa e sem responder?',
    subtexto: 'Perda temporária ou contínua do estado de alerta mental.',
    ativa: true,
    categoria: 'emergencia',
  },
  {
    id: 5,
    ordem: 5,
    texto: 'Existe sangramento abundante que não para com pressão local?',
    subtexto: 'Cortes profundos, hemorragias volumosas ou sangramentos contínuos.',
    ativa: true,
    categoria: 'emergencia',
  },
  {
    id: 6,
    ordem: 6,
    texto: 'Houve acidente grave, queda de grande altura ou trauma com suspected fratura?',
    subtexto: 'Acidentes de trânsito, lesões graves na cabeça, pescoço ou membros.',
    ativa: true,
    categoria: 'emergencia',
  },
  {
    id: 7,
    ordem: 7,
    texto: 'A situação clínica está piorando rapidamente com o passar das horas?',
    subtexto: 'Febre muito alta persistente com prostração extrema ou rápida degradação dos sintomas.',
    ativa: true,
    categoria: 'evolucao',
  },
];

export const MOCK_REGRAS: RegraTriagem[] = [
  {
    id: 1,
    perguntaId: 4,
    resposta: 'SIM',
    resultado: 'SAMU',
    prioridade: 1,
    mensagemOrientacao: 'Perda de consciência ou confusão súbita é uma emergência médica. Acione o SAMU 192 imediatamente.',
    sinalDeAlertaIdentificado: 'Relatada perda de consciência ou alteração súbita do nível de alerta.',
  },
  {
    id: 2,
    perguntaId: 3,
    resposta: 'SIM',
    resultado: 'SAMU',
    prioridade: 1,
    mensagemOrientacao: 'Dificuldade importante para respirar requer socorro de emergência imediato.',
    sinalDeAlertaIdentificado: 'Relatada dificuldade respiratória importante ou sensação de sufocamento.',
  },
  {
    id: 3,
    perguntaId: 2,
    resposta: 'SIM',
    resultado: 'UPA',
    prioridade: 2,
    mensagemOrientacao: 'Dor forte no peito precisa de avaliação médica urgente em unidade com eletrocardiograma e atendimento 24h.',
    sinalDeAlertaIdentificado: 'Relatada dor ou pressão forte no peito com potencial risco coronariano.',
  },
  {
    id: 4,
    perguntaId: 5,
    resposta: 'SIM',
    resultado: 'UPA',
    prioridade: 2,
    mensagemOrientacao: 'Sangramentos volumosos necessitam de contenção e atendimento de pronto socorro 24h.',
    sinalDeAlertaIdentificado: 'Relatado sangramento ativo e abundante.',
  },
  {
    id: 5,
    perguntaId: 6,
    resposta: 'SIM',
    resultado: 'UPA',
    prioridade: 2,
    mensagemOrientacao: 'Traumas e acidentes com dor intensa exigem exames de imagem e pronto atendimento imediato.',
    sinalDeAlertaIdentificado: 'Relatado trauma físico expressivo ou suspeita de lesão grave.',
  },
  {
    id: 6,
    perguntaId: 7,
    resposta: 'SIM',
    resultado: 'UPA',
    prioridade: 2,
    mensagemOrientacao: 'Quadros com rápida piora clínica se beneficiam da avaliação médica presencial continuada da UPA 24h.',
    sinalDeAlertaIdentificado: 'Relatado agravamento rápido do estado geral de saúde.',
  },
  {
    id: 7,
    perguntaId: 1,
    resposta: 'SIM',
    resultado: 'UPA',
    prioridade: 2,
    mensagemOrientacao: 'Sintomas súbitos e de forte intensidade devem ser avaliados com prioridade na UPA.',
    sinalDeAlertaIdentificado: 'Relatado início súbito e intenso dos sintomas.',
  },
];
